version: '3'

services:
  piper:
    image: linuxserver/piper:latest
    container_name: piper-tts
    volumes:
      - ./models:/config/models  # Changed from ./models/tts:/config/voices
      - ./output:/output
    environment:
      - PIPER_VOICE=en_US-joe-medium
      - PIPER_SPEAKER=0
    ports:
      - "10200:10200"
    restart: unless-stopped
